### ISSUE TITLE
GORENT-0001 - Configurar workflow CI com testes e análise de qualidade no SonarCloud

### ISSUE THREAD

**Issue by MateusOK** [MateusOK/GoRentApi.Net#1]
## 📋 Descrição:
Essa tarefa tem como objetivo configurar o pipeline de Integração Contínua (CI) do projeto GoRent (.NET) utilizando GitHub Actions. O CI será responsável por:

- Build da aplicação
- Execução dos testes automatizados
- Coleta da cobertura de código
- Análise de qualidade com o SonarCloud

Esse setup será feito com base em boas práticas atuais para garantir uma base sólida desde o início.

---

### ✅ Checklist:

- [x] **Criar arquivo `ci.yml` com estrutura de CI:**
  - Rodar build com `dotnet build`
  - Executar testes com `dotnet test`
  - Gerar relatório de cobertura com `coverlet`
  - Enviar análise para o SonarCloud

- [x] **Usar `fetch-depth: 0` para evitar shallow clone**

- [x] **Utilizar `SonarSource/sonarqube-scan-action@v5.0.0`**

- [x] **Utilizar `SONAR_TOKEN` no lugar de `sonar.login`**

- [x] **Gerar cobertura com formato compatível com Sonar (`opencover`)**

- [x] **Criar secrets no GitHub:**
  - `SONAR_TOKEN`

---

### 💡 Exemplo de workflow `.github/workflows/ci.yml`:

```yaml
name: CI - Build, Testes e Análise SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-analyze:
    name: Build e Análise SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Evita shallow clone para melhor rastreabilidade no SonarCloud

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build da aplicação
        run: dotnet build --no-restore --configuration Release

      - name: Executar testes com cobertura
        run: |
          dotnet test --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=./TestResults/coverage.opencover.xml

      - name: Análise com SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=MateusOK_GoRentApi_NET
            -Dsonar.organization=mateusok
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
```

---

### 🏁 Resultado esperado:

- CI rodando com sucesso a cada push/pull request para a `main`
- Relatório de cobertura visível no SonarCloud
- Qualidade de código monitorada com base nas regras definidas
- Base sólida para melhorias e escalabilidade do projeto
